Revert "[gnome-online-accounts] Use Meson."
This reverts commit d0a7ea5abc38c306b96938ecacd043391eee55aa.

Unbreak the build while it depends on an unreleased version of meson!
ERROR:  Meson version is 0.47.1 but project requires >= 0.47.2.