[3.0] Patch gupnp-av-0.7.1 so it builds successfully
Build failure was:
/usr/bin/ld: test-search-criteria-parser.o: undefined reference to
symbol 'g_signal_connect_data'