core-deps: Bump libical to 3.0.9
With newer versions of icu (libicu >= 68.1) libical 3.0.7
failes to compile due to removed public macro definitions
for TRUE and FALSE. So bump libical to 3.0.9.

This fixes build failure:

src/libical/icalrecur.c:1418:63: error: ‘FALSE’ undeclared