Fix AttributeError with python 3.14
pkgutil.get_loader was deprecated in python 3.12 and removed in 3.14.

Traceback (most recent call last):
  File "/home/mcatanzaro/.local/bin/jhbuild", line 36, in <module>
    jhbuild.main.main(sys.argv[1:])
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/main.py", line 118, in main
    rc = jhbuild.commands.run(command, config, args, help=lambda: print_help(parser))
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/commands/__init__.py", line 186, in run
    return cmd.execute(config, args, help)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/commands/__init__.py", line 53, in execute
    return self.run(config, options, args, help)
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/commands/base.py", line 320, in run
    module_set = jhbuild.moduleset.load(config)
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/moduleset.py", line 378, in load
    ms.modules.update(_parse_module_set(config, uri).modules)
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/moduleset.py", line 494, in _parse_module_set
    repo_class = get_repo_type(repo_type)
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/versioncontrol/__init__.py", line 195, in get_repo_type
    try_import_module('jhbuild.versioncontrol.%s' % name)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcatanzaro/Projects/jhbuild/jhbuild/utils/misc.py", line 52, in try_import_module
    if pkgutil.get_loader(module_name) is None:
       ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'get_loader'