[3.0] Patch gupnp-dlna-0.5.0 so it builds successfully
Build failure was:
/usr/bin/ld: gupnp-dlna-info.o: undefined reference to symbol
'gst_discoverer_audio_info_get_sample_rate'