core-deps: Bump wpe to 1.8.0
Debian testing/sid, Latest fedora and Arch has their webkit
built against wpe 1.8.0.  And so using 1.6.0 in jhbuild
conflicts with webkit when the system provided webkit is used

So bump libwpe and wpebackend-fdo to 1.8.0

This fixes build failure on link:

/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined reference to `wpe_fdo_initialize_shm'