apps-3.16: build libgda-5.2 without vala support
Vala support appears to be broken:

/home/mcatanzaro/jhbuild/install/bin/vapigen-0.28
--metadatadir=../libgda-ui --vapidir=../libgda --girdir=../libgda
--library=libgdaui-5.0 --pkg=libxml-2.0 --pkg=libgda-5.0 --pkg=gio-2.0
--pkg=atk --pkg=gtk+-3.0 Gdaui-5.0.gir
  GICOMP   Gdaui-5.0.gir
error: Package `libgda-ui-5.0' not found in specified Vala API
directories or GObject-Introspection GIR directories
Generation failed: 1 error(s), 0 warning(s)

Only anjuta uses libgda-5.2 and it does not require Vala support, so
let's just disable it.